platform :ios, '18.2'

source 'https://cdn.cocoapods.org/'

use_frameworks!

libsignal_ffi_prebuild_checksum = 'a3df979aa39b307ac4ef0f3fd59536daab5d6b3f8257c7aefe5f0470625f2582'

ENV['LIBSIGNAL_FFI_PREBUILD_CHECKSUM'] ||= libsignal_ffi_prebuild_checksum

target 'iosApp' do
  pod 'LibSignalClient', git: 'https://github.com/signalapp/libsignal.git', tag: 'v0.86.5'
end

post_install do |installer|
  installer.pods_project.targets
    .select { |target| target.name == 'LibSignalClient' }
    .each do |target|
      target.build_configurations.each do |configuration|
        configuration.build_settings['LIBSIGNAL_FFI_PREBUILD_CHECKSUM'] = libsignal_ffi_prebuild_checksum
      end
    end
end
